In [21]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/MyDrive/Attrition dataset"
import pandas as pd

AT_path = "/content/drive/MyDrive/Attrition dataset/Train.csv"
test_path  = "/content/drive/MyDrive/Attrition dataset/Test.csv"

Attrition_data = pd.read_csv(AT_path)
test  = pd.read_csv(test_path)

Attrition_data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
sample_submission.csv  Test.csv  Train.csv

,Employee_ID,Gender,Age,Education_Level,Relationship_Status,Hometown,Unit,Decision_skill_possess,Time_of_service,Time_since_promotion,...,Compensation_and_Benefits,Work_Life_balance,VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,Attrition_rate
0,EID_23371,F,42.0,4,Married,Franklin,IT,Conceptual,4.0,4,...,type2,3.0,4,0.7516,1.8688,2.0,4,5,3,0.1841
1,EID_18000,M,24.0,3,Single,Springfield,Logistics,Analytical,5.0,4,...,type2,4.0,3,-0.9612,-0.4537,2.0,3,5,3,0.0670
2,EID_3891,F,58.0,3,Married,Clinton,Quality,Conceptual,27.0,3,...,type2,1.0,4,-0.9612,-0.4537,3.0,3,8,3,0.0851
3,EID_17492,F,26.0,3,Single,Lebanon,Human Resource Management,Behavioral,4.0,3,...,type2,1.0,3,-1.8176,-0.4537,NaN,3,7,3,0.0668
4,EID_22534,F,31.0,1,Married,Springfield,Logistics,Conceptual,5.0,4,...,type3,3.0,1,0.7516,-0.4537,2.0,2,8,2,0.1827

In [22]:
# Data Cleaning step 1: drop useless columns
# Drop anonymized variables (VAR1 to VAR5)
var_cols = [col for col in Attrition_data.columns if col.startswith('VAR')]
Attrition_data.drop(columns=var_cols, inplace=True)
test.drop(columns=var_cols, inplace=True)
# Drop 'Hometown' as per project decision
Attrition_data.drop(columns='Hometown', inplace=True)
test.drop(columns='Hometown', inplace=True)

In [23]:
# Data Cleaning step 1: numericalize the metrics
# Encode the categories into numerical values
gender_map = {'M': 1, 'F': 0}
Attrition_data['Gender'] = Attrition_data['Gender'].map(gender_map)
test['Gender'] = test['Gender'].map(gender_map)

relationship_map = {'Single': 1, 'Married': 0}
Attrition_data['Relationship_Status'] = Attrition_data['Relationship_Status'].map(relationship_map)
test['Relationship_Status'] = test['Relationship_Status'].map(relationship_map)

decision_map = {
    'Conceptual': 1,
    'Analytical': 2,
    'Behavioral': 3,
    'Directive': 4
}
Attrition_data['Decision_skill_possess'] = Attrition_data['Decision_skill_possess'].map(decision_map)
test['Decision_skill_possess'] = test['Decision_skill_possess'].map(decision_map)

comp_map = {
    'type0': 1,
    'type1': 2,
    'type2': 3,
    'type3': 4,
    'type4': 5
}
Attrition_data['Compensation_and_Benefits'] = Attrition_data['Compensation_and_Benefits'].map(comp_map)
test['Compensation_and_Benefits'] = test['Compensation_and_Benefits'].map(comp_map)

unit_map = {
    'IT': 1,
    'Logistics': 1,
    'Quality': 1,
    'Security': 1,

    'Human Resource Management': 2,
    'Sales': 2,
    'Purchasing': 2,
    'Production': 2,
    'Operarions': 2,

    'Accounting and Finance': 3,
    'Marketing': 3,
    'R&D': 3
}

Attrition_data['Unit'] = Attrition_data['Unit'].map(unit_map)
test['Unit'] = test['Unit'].map(unit_map)

display(Attrition_data)
display(test)

,Employee_ID,Gender,Age,Education_Level,Relationship_Status,Unit,Decision_skill_possess,Time_of_service,Time_since_promotion,growth_rate,Travel_Rate,Post_Level,Pay_Scale,Compensation_and_Benefits,Work_Life_balance,Attrition_rate
0,EID_23371,0,42.0,4,0,1,1,4.0,4,33,1,1,7.0,3,3.0,0.1841
1,EID_18000,1,24.0,3,1,1,2,5.0,4,36,0,3,6.0,3,4.0,0.0670
2,EID_3891,0,58.0,3,0,1,1,27.0,3,51,0,2,8.0,3,1.0,0.0851
3,EID_17492,0,26.0,3,1,2,3,4.0,3,56,1,3,8.0,3,1.0,0.0668
4,EID_22534,0,31.0,1,0,1,1,5.0,4,62,1,3,2.0,4,3.0,0.1827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,EID_16328,0,23.0,5,0,2,3,4.0,1,20,1,2,6.0,4,3.0,0.7839
6996,EID_8387,0,44.0,1,0,3,2,16.0,2,59,0,2,4.0,4,3.0,0.1055
6997,EID_8077,0,49.0,3,1,1,4,10.0,1,59,1,2,3.0,3,4.0,0.7847
6998,EID_19597,0,47.0,3,0,2,3,24.0,1,21,1,5,8.0,1,2.0,0.4162
6999,EID_1640,0,58.0,3,0,1,4,22.0,2,74,0,4,5.0,3,3.0,0.0910

,Employee_ID,Gender,Age,Education_Level,Relationship_Status,Unit,Decision_skill_possess,Time_of_service,Time_since_promotion,growth_rate,Travel_Rate,Post_Level,Pay_Scale,Compensation_and_Benefits,Work_Life_balance
0,EID_22713,0,32.0,5,1,3,1,7.0,4,30,1,5,4.0,3,1.0
1,EID_9658,1,65.0,2,1,1,4,41.0,2,72,1,1,1.0,3,1.0
2,EID_22203,1,52.0,3,0,2,4,21.0,3,25,0,1,8.0,4,1.0
3,EID_7652,1,50.0,5,1,3,2,11.0,4,28,1,1,2.0,1,4.0
4,EID_6516,0,44.0,3,0,3,1,12.0,4,47,1,3,2.0,3,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,EID_22547,0,32.0,3,1,2,4,3.0,3,38,1,3,6.0,3,2.0
2996,EID_10066,0,NaN,2,1,3,1,10.0,2,57,1,4,9.0,3,1.0
2997,EID_7126,0,60.0,4,1,1,2,35.0,1,69,0,2,9.0,4,3.0
2998,EID_4929,0,51.0,1,0,1,3,23.0,1,30,0,2,6.0,4,1.0
2999,EID_24750,0,45.0,1,1,2,4,12.0,4,70,1,2,8.0,5,4.0

In [24]:
from sklearn.model_selection import cross_validate, KFold
from sklearn.pipeline        import Pipeline
from sklearn.impute          import SimpleImputer
from sklearn.preprocessing   import StandardScaler
from sklearn.linear_model    import LinearRegression, Ridge, Lasso
from sklearn.ensemble        import RandomForestRegressor, GradientBoostingRegressor
import numpy as np
import pandas as pd

# 1. Features & target (after your cleaning)
X = Attrition_data.drop(columns=['Employee_ID', 'Attrition_rate'])
y = Attrition_data['Attrition_rate']

# 2. Define 5-fold splitter
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 3. Build pipelines
pipelines = {
    'OLS': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('ols', LinearRegression())
    ]),
    'Ridge': Pipeline([
        ('imp',   SimpleImputer(strategy='mean')),
        ('scale', StandardScaler()),
        ('ridge', Ridge(alpha=1.0))
    ]),
    'Lasso': Pipeline([
        ('imp',   SimpleImputer(strategy='mean')),
        ('scale', StandardScaler()),
        ('lasso', Lasso(alpha=1.0, max_iter=10000))
    ]),
    'RandomForest': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('rf',  RandomForestRegressor(random_state=42))
    ]),
    'GBM': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('gb',  GradientBoostingRegressor(
                    n_estimators=100,
                    learning_rate=0.1,
                    max_depth=3,
                    random_state=42))
    ])
}

# 4. Define scoring metrics
scoring = {
    'MSE': 'neg_mean_squared_error',
    'MAE': 'neg_mean_absolute_error',
    'R2':  'r2'
}

# 5. Run cross-validation and collect results
results = {}
for name, pipe in pipelines.items():
    cv = cross_validate(pipe, X, y, cv=kf, scoring=scoring, return_train_score=False)
    results[name] = {
        'MSE_mean':  -np.mean(cv['test_MSE']),
        'MSE_std':    np.std(cv['test_MSE']),
        'MAE_mean':  -np.mean(cv['test_MAE']),
        'MAE_std':    np.std(cv['test_MAE']),
        'R2_mean':    np.mean(cv['test_R2']),
        'R2_std':     np.std(cv['test_R2']),
    }

# 6. Display as a DataFrame
cv_df = pd.DataFrame(results).T
print(cv_df)

              MSE_mean   MSE_std  MAE_mean   MAE_std   R2_mean    R2_std
OLS           0.034550  0.002500  0.127017  0.004538 -0.002085  0.004206
Ridge         0.034550  0.002500  0.127016  0.004538 -0.002084  0.004205
Lasso         0.034516  0.002409  0.126659  0.004416 -0.001270  0.001605
RandomForest  0.036419  0.002155  0.136555  0.003698 -0.057209  0.010324
GBM           0.035085  0.002517  0.128302  0.004259 -0.017663  0.007540

In [25]:
# Feature Engineering Method 1:
from sklearn.ensemble          import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.impute            import SimpleImputer
from sklearn.pipeline          import Pipeline

rf_pipe = Pipeline([
    ('imp', SimpleImputer(strategy='mean')),
    ('rf',  RandomForestRegressor(n_estimators=200, random_state=42))
])

# Fit on full data
rf_pipe.fit(X, y)

# Grab the fitted forest and select
rf = rf_pipe.named_steps['rf']
sfm = SelectFromModel(rf, threshold='median', prefit=True)

X_rf_sel = sfm.transform(X)
keep = X.columns[sfm.get_support()]
print("RF-selected:", list(keep))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(

RF-selected: ['Age', 'Education_Level', 'Time_of_service', 'growth_rate', 'Post_Level', 'Pay_Scale', 'Work_Life_balance']

In [26]:
# Feature Engineering Method 4:
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split
# evaluate on a hold-out set
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
rf_pipe.fit(X_train, y_train)

perm = permutation_importance(rf_pipe, X_val, y_val, n_repeats=10, random_state=42)
feat_imp = pd.Series(perm.importances_mean, index=X.columns).sort_values(ascending=False)
print(feat_imp.head())

Age                          0.043967
Time_of_service              0.036990
Compensation_and_Benefits    0.007148
Work_Life_balance            0.002456
Travel_Rate                  0.001688
dtype: float64

In [27]:
keep = [
  'Age',
  'Gender',
  'Time_of_service',
  'Travel_Rate',
  'Compensation_and_Benefits',
  'Time_since_promotion',
  'Work_Life_balance'
]
X_sub = Attrition_data[keep]
y     = Attrition_data['Attrition_rate']

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_sub, y, test_size=0.2, random_state=42
)

In [29]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# 3. Pipelines for each method
pipelines = {
    'OLS': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('ols', LinearRegression())
    ]),
    'Ridge': Pipeline([
        ('imp',   SimpleImputer(strategy='mean')),
        ('scale', StandardScaler()),
        ('ridge', Ridge(alpha=1.0, random_state=42))
    ]),
    'Lasso': Pipeline([
        ('imp',   SimpleImputer(strategy='mean')),
        ('scale', StandardScaler()),
        ('lasso', Lasso(alpha=0.01, random_state=42, max_iter=10000))
    ]),
    'RandomForest': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('rf',  RandomForestRegressor(n_estimators=200, random_state=42))
    ]),
    'GBM': Pipeline([
        ('imp', SimpleImputer(strategy='mean')),
        ('gb',  GradientBoostingRegressor(
                    n_estimators=200,
                    learning_rate=0.01,
                    max_depth=5,
                    random_state=42
                ))
    ]),
}

# 4. Scoring metrics
scoring = {
    'MSE': 'neg_mean_squared_error',
    'MAE': 'neg_mean_absolute_error',
    'R2':  'r2'
}

# 5. Cross-validate each pipeline
results = {}
for name, pipe in pipelines.items():
    cv = cross_validate(pipe, X_sub, y, cv=kf, scoring=scoring)
    mse_scores = -cv['test_MSE']
    mae_scores = -cv['test_MAE']
    r2_scores  =  cv['test_R2']
    results[name] = {
        'MSE_mean':  mse_scores.mean(),
        'MSE_std':   mse_scores.std(),
        'MAE_mean':  mae_scores.mean(),
        'MAE_std':   mae_scores.std(),
        'R2_mean':   r2_scores.mean(),
        'R2_std':    r2_scores.std(),
    }

# 6. Display results
cv_df = pd.DataFrame(results).T
print(cv_df)

              MSE_mean   MSE_std  MAE_mean   MAE_std   R2_mean    R2_std
OLS           0.034504  0.002498  0.126853  0.004541 -0.000733  0.004594
Ridge         0.034504  0.002498  0.126853  0.004541 -0.000732  0.004593
Lasso         0.034516  0.002409  0.126659  0.004416 -0.001270  0.001605
RandomForest  0.041114  0.002115  0.145086  0.003582 -0.194243  0.025886
GBM           0.034703  0.002349  0.127536  0.004123 -0.006830  0.004520

In [30]:
import numpy as np
import statsmodels.api as sm

# 1. Subset your columns of interest
keep = [
    'Age',
    'Gender',
    'Time_of_service',
    'Travel_Rate',
    'Compensation_and_Benefits',
    'Time_since_promotion',
    'Work_Life_balance'
]
X_sub = Attrition_data[keep].copy()
y     = Attrition_data['Attrition_rate'].copy()

# 2. Replace ±inf with NaN
X_sub.replace([np.inf, -np.inf], np.nan, inplace=True)
y.replace([np.inf, -np.inf], np.nan, inplace=True)

# 3. Drop any rows with NaN in X_sub or y
mask = X_sub.notna().all(axis=1) & y.notna()
X_sub = X_sub.loc[mask]
y     = y.loc[mask]

# 4. Add constant for intercept
X_const = sm.add_constant(X_sub)

# 5. Fit the OLS
model = sm.OLS(y, X_const).fit()

# 6. Print the summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Attrition_rate   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     2.591
Date:                Wed, 07 May 2025   Prob (F-statistic):             0.0115
Time:                        04:36:35   Log-Likelihood:                 1714.1
No. Observations:                6441   AIC:                            -3412.
Df Residuals:                    6433   BIC:                            -3358.
Df Model:                           7
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         0.1942      0.017     11.534      0.000       0.161       0.227
Age                           0.0003      0.000      0.736      0.462      -0.001       0.001
Gender                        0.0097      0.005      2.070      0.039       0.001       0.019
Time_of_service              -0.0008      0.001     -1.367      0.172      -0.002       0.000
Travel_Rate                  -0.0031      0.004     -0.863      0.388      -0.010       0.004
Compensation_and_Benefits    -0.0071      0.003     -2.243      0.025      -0.013      -0.001
Time_since_promotion          0.0026      0.002      1.256      0.209      -0.001       0.007
Work_Life_balance             0.0039      0.002      1.881      0.060      -0.000       0.008
==============================================================================
Omnibus:                     2623.928   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9931.571
Skew:                           2.062   Prob(JB):                         0.00
Kurtosis:                       7.473   Cond. No.                         331.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
# 1) Replace ±∞ with NaN
X = X.replace([np.inf, -np.inf], np.nan)
y = y.replace([np.inf, -np.inf], np.nan)

# 2) Drop any row with a missing value in X *or* y
mask = X.notna().all(axis=1) & y.notna()
X = X.loc[mask]
y = y.loc[mask]

# 3) Now add intercept and fit
X_const = sm.add_constant(X)
model   = sm.OLS(y, X_const).fit()

# 4) Print full summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Attrition_rate   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     1.934
Date:                Wed, 07 May 2025   Prob (F-statistic):             0.0190
Time:                        04:36:35   Log-Likelihood:                 1719.4
No. Observations:                6433   AIC:                            -3409.
Df Residuals:                    6418   BIC:                            -3307.
Df Model:                          14
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         0.1813      0.023      8.034      0.000       0.137       0.225
Gender                        0.0098      0.005      2.075      0.038       0.001       0.019
Age                           0.0003      0.000      0.718      0.473      -0.001       0.001
Education_Level              -0.0009      0.002     -0.416      0.678      -0.005       0.003
Relationship_Status           0.0052      0.005      1.076      0.282      -0.004       0.015
Unit                          0.0066      0.003      2.134      0.033       0.001       0.013
Decision_skill_possess       -0.0011      0.002     -0.511      0.609      -0.005       0.003
Time_of_service              -0.0008      0.001     -1.348      0.178      -0.002       0.000
Time_since_promotion          0.0027      0.002      1.349      0.177      -0.001       0.007
growth_rate                5.557e-05      0.000      0.378      0.705      -0.000       0.000
Travel_Rate                  -0.0034      0.004     -0.954      0.340      -0.010       0.004
Post_Level                    0.0028      0.002      1.431      0.152      -0.001       0.007
Pay_Scale                    -0.0009      0.001     -0.825      0.410      -0.003       0.001
Compensation_and_Benefits    -0.0072      0.003     -2.263      0.024      -0.013      -0.001
Work_Life_balance             0.0039      0.002      1.885      0.060      -0.000       0.008
==============================================================================
Omnibus:                     2610.486   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9837.815
Skew:                           2.054   Prob(JB):                         0.00
Kurtosis:                       7.452   Cond. No.                         643.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [32]:
import numpy as np
import statsmodels.api as sm

# 1. Compute new features in-place
Attrition_data['Age_sq']          = Attrition_data['Age'] ** 2
Attrition_data['log_Travel_Rate'] = np.log(Attrition_data['Travel_Rate'] + 1)
Attrition_data['Gender_x_Comp']   = (
    Attrition_data['Gender'] *
    Attrition_data['Compensation_and_Benefits']
)

# 2. Build design matrix including the new columns
keep_ext    = keep + ['Age_sq', 'log_Travel_Rate', 'Gender_x_Comp']
X_sub_ext   = Attrition_data[keep_ext].copy()
y           = Attrition_data['Attrition_rate'].copy()

# 3. Replace inf with NaN, then drop any row with NaN
X_sub_ext.replace([np.inf, -np.inf], np.nan, inplace=True)
y.replace([np.inf, -np.inf], np.nan, inplace=True)

mask = X_sub_ext.notna().all(axis=1) & y.notna()
X_sub_ext = X_sub_ext.loc[mask]
y         = y.loc[mask]

# 4. Add intercept and re‑fit OLS
X_const_ext = sm.add_constant(X_sub_ext)
model_ext   = sm.OLS(y, X_const_ext).fit()

# 5. Print summary
print(model_ext.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Attrition_rate   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     2.387
Date:                Wed, 07 May 2025   Prob (F-statistic):            0.00804
Time:                        04:36:35   Log-Likelihood:                 1717.0
No. Observations:                6441   AIC:                            -3412.
Df Residuals:                    6430   BIC:                            -3337.
Df Model:                          10
Covariance Type:            nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
const                         0.1982      0.028      7.108      0.000       0.144       0.253
Age                          -0.0007      0.001     -0.528      0.598      -0.003       0.002
Gender                        0.0469      0.022      2.099      0.036       0.003       0.091
Time_of_service              -0.0010      0.001     -1.595      0.111      -0.002       0.000
Travel_Rate                   0.0255      0.020      1.262      0.207      -0.014       0.065
Compensation_and_Benefits    -0.0027      0.004     -0.649      0.516      -0.011       0.005
Time_since_promotion          0.0030      0.002      1.429      0.153      -0.001       0.007
Work_Life_balance             0.0040      0.002      1.933      0.053   -5.65e-05       0.008
Age_sq                      1.34e-05    1.6e-05      0.839      0.402   -1.79e-05    4.47e-05
log_Travel_Rate              -0.0489      0.034     -1.438      0.151      -0.115       0.018
Gender_x_Comp                -0.0110      0.006     -1.701      0.089      -0.024       0.002
==============================================================================
Omnibus:                     2623.684   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9939.792
Skew:                           2.061   Prob(JB):                         0.00
Kurtosis:                       7.477   Cond. No.                     3.56e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.56e+04. This might indicate that there are
strong multicollinearity or other numerical problems.